services:
  react-app-dev:
    image: kiransuresh12/react-app-dev:latest
    container_name: react-app-dev
    ports:
      - "80:80"

  react-app-prod:
    image: kiransuresh12/react-app-prod:latest
    container_name: react-app-prod
    ports:
      - "8080:80"
